### ISSUE TITLE
Use of unresolved identifier 'Message'

### ISSUE THREAD

**Issue by charbelyoussef** [Debashish3100/RichNotification#1]
Use of unresolved identifier 'Message' in the NotificationService class

**Comment by Debashish3100** [comment]
![Screenshot 2021-02-09 at 12 31 51 PM](https://user-images.githubusercontent.com/52688868/107327316-f457c000-6ad2-11eb-905e-756c622e2437.png)
Actually I am saving the notification to coredata within NotificationService class. Thats why I have used ManagedObject subclass 'Message'. You can comment out that one. Hope it helps

**Comment by charbelyoussef** [comment]
Hello,

Thanks for your response man.
It's all good now.

Best,
Charbel.
